### ISSUE TITLE
GTP-U Extension Header missing?

### ISSUE THREAD

**Issue by mmailand** [hhorai/gnbsim#15]
Hello @hhorai,

I try to establish a GTP session between the gnbsim and the UPF from the Open5gs 5G Core. Right now the UPF discards the GTP packets from gnbsim. I think because of the missing extension header (PDU Session Container). I think the format is described here https://www.etsi.org/deliver/etsi_ts/138400_138499/138415/15.00.00_60/ts_138415v150000p.pdf 

I also attach two pcaps, one from the gnbsim with the Open5gs core, and one from a 
commercial tester with the Open5gs core. 

What do you think about that? How is free5gc handling this?

Best regards.

[upf.pcap.gz](https://github.com/hhorai/gnbsim/files/5372392/upf.pcap.gz)
[upf_working.pcap.gz](https://github.com/hhorai/gnbsim/files/5372393/upf_working.pcap.gz)

**Comment by mmailand** [comment]
Hello @hhorai,
I digged a little deeper into this issue and I can now verify that the missing extension header is the reason for the UPF discarding the packets. 
I was able to create the correct packets with scapy and the UPF forwarded those packets. 
In the attached pcap file you can see that packet 18 and 19 (create from gnbsim) are discarded by the UPF, packet 46 is a packet crafted with scapy which includes the extension header, and the UPF is forwarding this packet.

The scapy config is:
send(IP(src="192.168.199.207", dst="192.168.199.208")/UDP(sport=2152,dport=2152)/GTPHeader(teid=1, E=1, gtp_type=255, next_ex=133)/GTPPDUSessionContainer(type=1, QFI=1)/IP(src="10.46.0.2", dst="192.168.100.11")/TCP(sport=6666,dport=80))

I hope that helps you.

Best regards.

[upf.pcap.gz](https://github.com/hhorai/gnbsim/files/5377137/upf.pcap.gz)

**Comment by hhorai** [comment]
Hi, @mmailand 

Thank you for reporting the issue. As you mentioned above, It seems to be a problem for gnbsim.
At this moment, gnbsim works with gtp linux kernel module, but I think that the module doesn't have GTP extension header capability. On the other hand I know `PrinzOwO/gtp5g` that is used in `free5gc/free5gc`, but it isn't capable of extension header too. Therefore I think I will try to implement userland gtp in my repository, but it will take some time.

If you know another good solution, could you please tell me about it. I would like to study it.

Thanks,

**Comment by hhorai** [comment]
Hello, @mmailand 

I have implemented the GTP parser on my own at hhorai/gnbsim@ba4ca20. Now the gnbsim sends a GTP packet with an extension header. It is helpful for me If you could try again when you have time.

Thank you,

**Comment by mmailand** [comment]
Hello @hhorai,

I tried the version you mentioned above, but I get this error:

```
[gnbsim]2020/11/20 09:51:46.448364 example.go:90: write: len 40, info: &{Stream:0 SSN:5 Flags:0 _:0 PPID:0 Context:0 TTL:0 TSN:4113700940 CumTSN:0 AssocID:21}
[gnbsim]2020/11/20 09:51:49.449518 example.go:290: GTPuIFname: net1
[gnbsim]2020/11/20 09:51:49.449640 example.go:291: GTP-U Peer: 10.0.22.102
[gnbsim]2020/11/20 09:51:49.449659 example.go:292: GTP-U Peer TEID: 8
[gnbsim]2020/11/20 09:51:49.449673 example.go:293: GTP-U Local TEID: 2596996162
[gnbsim]2020/11/20 09:51:49.449686 example.go:294: QoS Flow ID: 1
[gnbsim]2020/11/20 09:51:49.449717 example.go:295: UE address: 10.46.0.5
test: gNB UDP local address: 10.0.22.100:2152
runUPlane
[gnbsim]2020/11/20 09:51:49.453033 example.go:506: read /dev/net/tun: not pollable
```

I am not sure if this is an issue with gnbsim, or with my setup, how I use gnbsim.
I run gnbsim in Kubernetes, but I did so as well in the previous tests.

I gave the gnbsim container higher privileges and mounted the /dev/net/tun device as well.

```
  spec:
      containers:
        - name: gnbsim
          image: martinmailand/gnbsim:latest
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "900000"]
          volumeMounts:
          - name: dev-net-tun
            mountPath: /dev/net/tun
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
```
Do you have any insight here?

Full log of the gnbsim run ist attached.

[gnbsim.log.gz](https://github.com/hhorai/gnbsim/files/5572781/gnbsim.log.gz)
